#  This file is part of Socialvoid.NET Project (https://github.com/Intellivoid/Socialvoid.NET).
#  Copyright (c) 2021 Socialvoid.NET Authors.
# 
#  This library is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3.
# 
#  This library is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this source code of library. 
#  If not, see <http://www.gnu.org/licenses/>.

version: 2
updates:
- package-ecosystem: nuget
  directory: "/Socialvoid"
  schedule:
    interval: daily
    time: "15:00"
    timezone: "UTC"
  open-pull-requests-limit: 25
  labels: ["Dependency"]
  milestone: 1
  pull-request-branch-name: 
    separator: "-"
  reviewers: ["ALiwoto", "Dank-del"]
  target-branch: "master"

